{% set name = "TA-lib-zipline" %}
{% set version = "0.4.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: c4f1391ad7ac4b2f248fdc973e62fab8

build:
  number: 0
  skip: true # [py<37 or not x86_64]
  include_recipe: False

requirements:
  build:
    - python
    - setuptools_scm
    - cython
    - numpy<1.23
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - numpy <1.23

test:
  imports:
    - talib

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License
